#!/bin/bash

# this program is called by make test.
# It takes all given sudoku data sets
# and checks that for each of them
# the basic solver gives the exact same
# output as the advanced solver. In case
# the outputs differ, the result is placed
# into res/ directory.

make
basic=./sudoku_solver
adv=./sudoku_advanced
result=0

outfolder=res
mkdir -p "$outfolder"

run_test() {
  file=$1; shift
  out1=$($basic < "$file")
  out2=$($adv < "$file")
  if [ "$out1" != "$out2" ]; then
    echo "fail!"
    {
      cat "$file"
      echo "------------"
      echo "$out1"
      echo "------------"
      echo "$out2"
    } > "$outfolder/$(basename "$file")"
  fi
}

maxthreads=$(getconf _NPROCESSORS_ONLN)
nthreads=0
test_dir() {
  dir=$1; shift
  [ -d "$dir" ] || {
	echo "no such directory: $dir"
	return 0
  }
  for f in $dir/*; do
    [ "$nthreads" -ge "$maxthreads" ] && {
      wait
      nthreads=0
    }
    [ "$result" -ne 0 ] && return 1
    echo "$f"
    run_test "$f" &
    ((++nthreads))
  done
  wait
}

main() {
  for f in $(find ../tests -name "*.in" | grep '[123]_' | grep -v "very_hard_1.in"); do
    echo "$f"
    run_test "$f"
  done
  test_dir ./tests
  test_dir ./test3_hard
  test_dir ./test3_1465
  test_dir ./test3_gen
  echo
  no_files=$(ls res/ | wc -l)
  [ "$no_files" -eq 0 ] && {
    echo "success"
  } || {
    for f in res/*;do
      echo "problem file: $f"
    done
  }
}

main
